sudo: required
services:
  - docker

before_install:
  - docker build -t ethomatos/docker-react -f Dockerfile.dev .

script:
  - docker run ethomatos/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "et-docker-react"
  env: "EtDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-601427279990"
  bucket_path: "et-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
